### ISSUE TITLE
 Identical images  all_relevant_matches is None

### ISSUE THREAD

**Issue by zhangjunqiang** [OpenStitching/stitching_tutorial#12]
In the tutorial code.
I modified the code in the _Resize Images_ of the tutorial. 
```python
...
img_handler = ImageHandler()
img_handler.set_img_names(['imgs/weir_1.jpg', 'imgs/weir_1.jpg'])
...
```
I used two identical images in the code.
but i found that the result print in the _Match Features_ section is.
```python
matcher.get_confidence_matrix(matches)
```
```
[[0. 0.]
 [0. 0.]]
```
and the all_relevant_matches is None.

In my intuition，the confidence_matrix of two identical images should be very high. am i wrong?

**Comment by lukasalexanderweber** [comment]
Just a few questions so I can follow:

In the [Find Features](https://github.com/OpenStitching/stitching_tutorial/blob/master/docs/Stitching%20Tutorial.md#find-features) section, `plot_image(keypoints_center_img, (15,10))` plots the image with the features?

Just that I can be sure that there is no error before.

I don't know if two identical images have a high confidence, but I guess they should

**Comment by zhangjunqiang** [comment]
> 
This is the test code:
```python 
import os

import mpld3
from matplotlib import pyplot as plt
import cv2 as cv
import numpy as np


def plot_image(img, figsize_in_inches=(5, 5)):
    fig, ax = plt.subplots(figsize=figsize_in_inches)
    ax.imshow(cv.cvtColor(img, cv.COLOR_BGR2RGB))
    plt.show()


def plot_images(imgs, figsize_in_inches=(5, 5)):
    fig, axs = plt.subplots(1, len(imgs), figsize=figsize_in_inches)
    for col, img in enumerate(imgs):
        axs[col].imshow(cv.cvtColor(img, cv.COLOR_BGR2RGB))
    plt.show()



# Resize Images
from stitching.image_handler import ImageHandler

img_handler = ImageHandler()
img_handler.set_img_names(['images/weir_1.jpg', 'images/weir_1.jpg'])

medium_imgs = list(img_handler.resize_to_medium_resolution())

# Find Features
from stitching.feature_detector import FeatureDetector

finder = FeatureDetector("sift")
features = [finder.detect_features(img) for img in medium_imgs]
keypoints_center_img = finder.draw_keypoints(medium_imgs[1], features[1])


# Match Features
from stitching.feature_matcher import FeatureMatcher

matcher = FeatureMatcher()
matches = matcher.match_features(features)
print(matcher.get_confidence_matrix(matches))
all_relevant_matches = matcher.draw_matches_matrix(medium_imgs, features, matches, conf_thresh=1,
                                                   inliers=True, matchColor=(0, 255, 0))

print(all_relevant_matches)
# triple = list(all_relevant_matches)[0]
# print(f"Matches Image {triple[0]} to Image {triple[1]}")
# plot_image(triple[2], (20,10))
for idx1, idx2, img in all_relevant_matches:
    print(f"Matches Image {idx1+1} to Image {idx2+1}")
    plot_image(img, (20,10))

````

I did't write the ``` plot_image(keypoints_center_img, (15,10))``` code to the test code.

but after add the plot code to the end of _Find Features_.
it plot the pic like this(with no error):
![image](https://github.com/OpenStitching/stitching_tutorial/assets/5388898/63cf1ff8-99f2-4230-b696-778bff20a401)

**Comment by lukasalexanderweber** [comment]
I would need to do some research why there is no confidence between identical Images. Why would you want to stitch them?

**Comment by zhangjunqiang** [comment]
> 
i was build a similar images search system. first step is search similar images from images storage. second step is Match Features with the similar images(like the tutorial Matches Image 1 to Image 2).  this is the end.
i will not stitch them to a image. i just match features from similar images(like below image). 

![image](https://github.com/OpenStitching/stitching_tutorial/assets/5388898/a6592f95-97a0-43f7-a871-9fbce371e411)

**Comment by lukasalexanderweber** [comment]
since this is not in the scope of this package I will close this issue.
