### ISSUE TITLE
Problems with running "cropper.estimate_panorama_mask"

### ISSUE THREAD

**Issue by MartinReinhard10** [OpenStitching/stitching_tutorial#13]
Hi,

First of all, thank you very much for the detailed tutorial on image stitching!
However, i am having an issue with one project that I hope you might be able to clarify for me.

I have a set of 10 images that need to be stitched together both vertically and horizontally. When i run the stitcher class i get good results and the images are correctly stitched (see below).

```
from stitching import Stitcher
settings = {# The whole plan should be considered
            "crop": False,
            # The matches confidences aren't that good
            "confidence_threshold": 0.5,
            "detector": "sift"} 

stitcher = Stitcher(**settings)
panorama = stitcher.stitch(images)
```

![image](https://github.com/OpenStitching/stitching_tutorial/assets/107025473/e8df65be-52c5-42f1-bc6c-7d51ace5d3c8)

But when i try to redo the steps in the tutorial i get stuck when using the following code which seems to create a "wrong" mask for the stitching:
```
from stitching.cropper import Cropper

cropper = Cropper()
mask = cropper.estimate_panorama_mask(warped_low_imgs, warped_low_masks, low_corners, low_sizes)
plot_image(mask, (5,5))
```
![image](https://github.com/OpenStitching/stitching_tutorial/assets/107025473/9164826b-e1cd-4d5c-8602-4562ddaacdd9)

This further results in errors when using the SeamFinder. 

error                                     Traceback (most recent call last)
Cell In[22], line 5
      1 from stitching.seam_finder import SeamFinder
      3 seam_finder = SeamFinder()
----> 5 seam_masks = seam_finder.find(low_imgs, low_corners, mask)
      6 seam_masks = [seam_finder.resize(seam_mask, mask) for seam_mask, mask in zip(seam_masks, mask)]
      8 seam_masks_plots = [SeamFinder.draw_seam_mask(img, seam_mask) for img, seam_mask in zip(final_imgs, seam_masks)]

File [~\AppData\Roaming\Python\Python310\site-packages\stitching\seam_finder.py:33](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/au519867/OneDrive%20-%20Aarhus%20universitet/Skrivebord/In-Situ-Soil_Optode/~/AppData/Roaming/Python/Python310/site-packages/stitching/seam_finder.py:33), in SeamFinder.find(self, imgs, corners, masks)
     31 def find(self, imgs, corners, masks):
     32     imgs_float = [img.astype(np.float32) for img in imgs]
---> 33     return self.finder.find(imgs_float, corners, masks)

error: OpenCV(4.7.0) [D:\a\opencv-python\opencv-python\opencv\modules\stitching\src\seam_finders.cpp:241](file:///D:/a/opencv-python/opencv-python/opencv/modules/stitching/src/seam_finders.cpp:241): error: (-215:Assertion failed) image1.size() == mask1.size() in function 'cv::detail::DpSeamFinder::process'

Again, thank you for the great tutorial. It works perfect, but I would like to understand and get the individual steps working also :) 
Please let me know if i can provide more information to assist you.

Best,
Martin

**Comment by lukasalexanderweber** [comment]
Is this still relevant. Sorry for the late feedback

**Comment by MartinReinhard10** [comment]
No Problem. 
I still have the issue with not getting the correct panorama mask.

**Comment by MartinReinhard10** [comment]
Yes, the complete workflow works perfectly. it is only when following the tutorial that I cant get the same result.

The time series does not look great. So I guess it's an issue with the image matching in previous steps?

This is working for me:

`from stitching import Stitcher
settings = {# The whole plan should be considered
            "crop": False,
            # The matches confidences aren't that good
            "confidence_threshold": 0.5,
            "detector": "sift"} 
stitcher = Stitcher(**settings)
panorama = stitcher.stitch(images)`

And these are my settings for the image feature detector and subsetter in the tutorial:

`from stitching.feature_detector import FeatureDetector
finder = FeatureDetector(detector="sift",nfeatures=5000)
features = [finder.detect_features(img) for img in medium_imgs]
keypoints_img = finder.draw_keypoints(medium_imgs[1], features[1],)`

`subsetter = Subsetter(confidence_threshold=0.5, matches_graph_dot_file=None)
dot_notation = subsetter.get_matches_graph(img_handler.img_names, matches)
print(dot_notation)`

**Comment by MartinReinhard10** [comment]
[https://www.dropbox.com/scl/fo/frdu2wgjee21yp8cei30g/h?rlkey=dyzqpwwr3un7y55gge57i0wry&dl=0](url)

**Comment by lukasalexanderweber** [comment]
Could you please share the error occuring when cropping is enabeld in the complete workflow

**Comment by MartinReinhard10** [comment]
Hmm, it actually also works fine with the crop enabled. I must have remembered it wrong. sorry about that. it have been a while since i tried it out the first time.

**Comment by MartinReinhard10** [comment]
So i think the issue is in the image-matching process. but why they are different in the two methods i am not sure about.

**Comment by lukasalexanderweber** [comment]
You set nfeatures to 5000, default is 500, maybe thats an issue. The both matches graphs would also be great for comparison.
